set "PREFIX_CYG=%PREFIX:\=/%"
set "PREFIX_CYG=/%PREFIX_CYG::=%"
set "LIBRARY_PREFIX_CYG=%LIBRARY_PREFIX:\=/%"
set "LIBRARY_PREFIX_CYG=/%LIBRARY_PREFIX_CYG::=%"

"%R%" CMD INSTALL --build .
IF %ERRORLEVEL% NEQ 0 exit 1
