{% set version = '0.7-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:  # [not win]
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz  # [not win]
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz  # [not win]
  sha256: 356a1c6758b823f8d2712e65d2dd45279d52070832dc158ed0b87916129a0b1d  # [not win]

  url: https://cran.r-project.org/bin/windows/contrib/{{ r_base[0:3] }}/sf_{{ version }}.zip  # [win]
  sha256: 62bcf0cfbbb36a04491f6d61b0acd5715b894ef0516193d1d3f69483470115df  # [win]

build:
  number: 0
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj4  # [not win]
    - pkg-config  # [not win]
  run:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj4  # [not win]
    - pkg-config  # [not win]

test:
  commands:
    - $R -e "library('sf')"  # [not win]
    - R -e \"library('sf')\"  # [win]

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2.0 | MIT
  license_file: LICENSE
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds
    to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and
    to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid
