{% set version = '0.7-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  fn: sf_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: d859d3da962ee58fc5f67ad3c557b90fa333849523e52256e01ec020c2f2cc9e

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32 or vc<14]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal

test:
  commands:
    - $R -e "library('sf')"  # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

about:
  home: https://github.com/edzer/sfr/
  license: GPL-2
  summary: |
    Support for simple features, a standardized way to encode spatial vector data.
    Binds to GDAL for reading and writing data, to GEOS for geometrical operations, and to Proj.4
    for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
