{% set version = "1.0-17" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: 22c7c2d2e98a6142e4beff07e70c169238257312e6eb3591b129ed3c7d18b286

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-classint                   # [build_platform != target_platform]
    - r-dbi                        # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-s2                         # [build_platform != target_platform]
    - r-units                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-classint >=0.4_1
    - r-dbi >=0.8
    - r-magrittr
    - r-rcpp >=0.12.18
    - r-s2 >=1.1.0
    - r-units >=0.7_0
    - geos
    - libgdal
    - proj
  run:
    - r-base
    - r-classint >=0.4_1
    - r-dbi >=0.8
    - r-magrittr
    - r-rcpp >=0.12.18
    - r-s2 >=1.1.0
    - r-units >=0.7_0

test:
  commands:
    - $R -e "library('sf')"           # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

about:
  home: https://r-spatial.github.io/sf/
  dev_url: https://github.com/r-spatial/sf/
  license: GPL-2.0-only OR MIT
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
