{% set version = '0.7-4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  fn: sf_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: 2112281803b2f87dfb33cf20825d960cb4e9084533acbc26128932e7fbc9de6e

build:
  skip: True  # [win]
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{posix}}autoconf
    - {{posix}}automake
    - {{posix}}pkg-config
    - {{posix}}make
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-units >=0.6_0
    - libgdal
    - proj4
  run:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal
    - proj4

test:
  commands:
    - $R -e "library('sf')"

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2.0 | MIT
  license_file: LICENSE
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds
    to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and
    to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid
