{% set version = '0.7-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: d859d3da962ee58fc5f67ad3c557b90fa333849523e52256e01ec020c2f2cc9e

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - gdal                       # [win]
    - libgdal                    # [unix]
    - proj4                      # [unix]
    - geos >=3.6.2,<3.6.3.0a0    # [unix]
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - gdal                       # [win]
    - libgdal                    # [unix]
    - proj4                      # [unix]
    - geos >=3.6.2,<3.6.3.0a0    # [unix]
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0

test:
  commands:
    - $R -e "library('sf')"           # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2 | MIT
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds
    to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and
    to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sf
# Version: 0.7-2
# Date: 2018-11-24
# Title: Simple Features for R
# Authors@R:  c(person(given = "Edzer", family = "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de", comment = c(ORCID = "0000-0001-8049-7069")), person(given = "Roger", family = "Bivand", role = "ctb", comment = c(ORCID = "0000-0003-2392-6140")), person(given = "Etienne", family = "Racine", role = "ctb"), person(given = "Michael", family = "Sumner", role = "ctb"), person(given = "Ian", family = "Cook", role = "ctb"), person(given = "Tim", family = "Keitt", role = "ctb"), person(given = "Robin", family = "Lovelace", role = "ctb"), person(given = "Hadley", family = "Wickham", role = "ctb"), person(given = "Jeroen", family = "Ooms", role = "ctb", comment = c(ORCID = "0000-0002-4035-0289")), person(given = "Kirill", family = "Muller", role = "ctb"))
# Description: Support for simple features, a standardized way to encode spatial vector data. Binds to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and to 'PROJ' for projection conversions and datum transformations.
# License: GPL-2 | MIT + file LICENSE
# URL: https://github.com/r-spatial/sf/
# BugReports: https://github.com/r-spatial/sf/issues/
# Depends: methods, R (>= 3.3.0)
# Imports: classInt (>= 0.2-1), DBI (>= 0.8), graphics, grDevices, grid, magrittr, Rcpp, stats, tools, units (>= 0.6-0), utils
# Suggests: blob, covr, dplyr (>= 0.7-0), ggplot2, knitr, lwgeom (>= 0.1-5), maps, maptools, mapview, microbenchmark, odbc, pillar, pool, raster, rgdal, rgeos, rlang, rmarkdown, RPostgres (>= 1.1.0), RPostgreSQL, RSQLite, sp (>= 1.2-4), spatstat, stars (>= 0.2-0), testthat, tibble (>= 1.4.1), tidyr (>= 0.7-2), tidyselect, tmap (>= 2.0)
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# SystemRequirements: C++11, GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ (>= 4.8.0)
# Collate: 'RcppExports.R' 'init.R' 'crs.R' 'bbox.R' 'read.R' 'db.R' 'sfc.R' 'sfg.R' 'sf.R' 'bind.R' 'wkb.R' 'wkt.R' 'plot.R' 'geom.R' 'transform.R' 'sp.R' 'grid.R' 'arith.R' 'tidyverse.R' 'cast_sfg.R' 'cast_sfc.R' 'graticule.R' 'datasets.R' 'aggregate.R' 'agr.R' 'maps.R' 'join.R' 'sample.R' 'valid.R' 'collection_extract.R' 'jitter.R' 'sgbp.R' 'spatstat.R' 'stars.R' 'crop.R' 'gdal_utils.R' 'nearest.R' 'deprecated.R'
# NeedsCompilation: yes
# Packaged: 2018-12-20 08:55:02 UTC; edzer
# Author: Edzer Pebesma [aut, cre] (<https://orcid.org/0000-0001-8049-7069>), Roger Bivand [ctb] (<https://orcid.org/0000-0003-2392-6140>), Etienne Racine [ctb], Michael Sumner [ctb], Ian Cook [ctb], Tim Keitt [ctb], Robin Lovelace [ctb], Hadley Wickham [ctb], Jeroen Ooms [ctb] (<https://orcid.org/0000-0002-4035-0289>), Kirill Muller [ctb]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2018-12-20 10:10:03 UTC
