# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YPx9xJigzNc288wi6a06+MF9d5rOVB+x7OryW++AO8B8jHbv/NNl1rIAXYyEh+6We3qjBghY0pSu0Er0jFda30lGgTnMnnVRaXhcdvb3JQcviw3sxR8UpG3NKSVKYuYA4PWyHEfywIWumuyHQ353jU2WIEp2WU4vEE/oHlxAFt6HhqxvEYU1GEDS6vc9jYaiDhEnMAUm8eCPlLxTLc5O+CnUpBP0zmrEMVcaAtnjB3pcmhzOfbAcWm73Eck8TmZGdvQD5f4enwWPIUJ/ahKNNXIHmfMUbz/ZgfgQXOMP9DSYOiXJTwc6S5IcfqNeuSaIhHx4ALTkzr7cUz8KLVfg07urlqMwtZgpdGLiBLE5YUDlALQVZzaSCdPK1ayG4EeBxbIsXrbOUEUNcJ5Zp+0Imu3tvAPz/gaOIIg/N3xRspoXfSjx/XsQsGm6SvCttURCW+UZ6QF2Prj05Zioln/bUYNADbshtlMN2Dwd5iGbiQ5oNwGZkrVNk9yLgVayJCOo3hi1h6Vm6ioDZIaypayq0tLgF+bvWrWMcEydHCCCDePh1nu765kb3YyH/aWNWglsqNk/+Ucu2DmQnRErQVN3LAib6SiuGdLY0mRSc1v9gOFa1E+esDUu+hCxlqR6Om7WnSZaHyyV6fGbyPU/iaffhMihj2ZVZ8tKVfpbKze09Xc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
