bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
